export const DIRECTION_UP = "DIRECTION_UP"
export const DIRECTION_DOWN = "DIRECTION_DOWN"
export const DIRECTION_LEFT = "DIRECTION_LEFT"
export const DIRECTION_RIGHT = "DIRECTION_RIGHT"
export const UNICODE_UP_ARROW = "▲"
export const UNICODE_DOWN_ARROW = "▼"
export const UNICODE_LEFT_ARROW = "◀"
export const UNICODE_RIGHT_ARROW = "▶"
export const INPUT_TYPE_DIRECTION = "INPUT_TYPE_DIRECTION"
export const INPUT_TYPE_ACTION = "INPUT_TYPE_ACTION"
export const INPUT_DIRECTION_UP = { key: "INPUT_DIRECTION_UP", type: INPUT_TYPE_DIRECTION, direction: DIRECTION_UP }
export const INPUT_DIRECTION_DOWN = { key: "INPUT_DIRECTION_DOWN", type: INPUT_TYPE_DIRECTION, direction: DIRECTION_DOWN }
export const INPUT_DIRECTION_LEFT = { key: "INPUT_DIRECTION_LEFT", type: INPUT_TYPE_DIRECTION, direction: DIRECTION_LEFT }
export const INPUT_DIRECTION_RIGHT = { key: "INPUT_DIRECTION_RIGHT", type: INPUT_TYPE_DIRECTION, direction: DIRECTION_RIGHT }
export const INPUT_ACTION_PRIMARY = { key: "INPUT_ACTION_PRIMARY", type: INPUT_TYPE_ACTION }

export const BASE_FUNCTIONS_URL = "https://romantic-engelbart-90b7b9.netlify.app/.netlify/functions/"